### ISSUE TITLE
Tag > Failed to add node: Duplicate key for property id: tag1

### ISSUE THREAD

**Issue by paulvanbladel** [noxify/gridsome-starter-articles#7]
Very nice template.
After installation, getting following error.
Not (yet) familiar enough with gridsome to find the root cause myself :(
```
$ gridsome develop
Gridsome v0.7.19


Initializing plugins...
Tag > Failed to add node: Duplicate key for property id: tag1
Tag > Failed to add node: Duplicate key for property id: tag2
Tag > Failed to add node: Duplicate key for property id: tag3
Tag > Failed to add node: Duplicate key for property id: tag4
Tag > Failed to add node: Duplicate key for property id: tag5
Load sources - 0.11s
Create GraphQL schema - 0.09s
Create pages and templates - 0.05s
Generate temporary code - 0.02s
Bootstrap finish - 0.9s
code block or inline code language not specified in markdown. applying generic code block
 ERROR  Failed to compile with 3 errors10:29:51

 error  in ./src/templates/ArticleEntry.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Variable "$tags" of type "[String]" used in position expecting type "[ID]".

GraphQL request:42:31
41 |
42 | query Article($recordId: ID!, $tags: [String]) {
   |                               ^
43 |   entry : article(id: $recordId) {

GraphQL request:61:58
60 |   related: allArticle(
61 |     filter: { id: { ne: $recordId }, tags: {containsAny: $tags} }
   |                                                          ^
62 |   ) {
    at Object.module.exports (D:\github\discorso\node_modules\gridsome\lib\plugins\vue-components\lib\loaders\page-query.js:33:23)

 @ ./src/templates/ArticleEntry.vue?vue&type=custom&index=0&blockType=page-query 1:0-338 1:354-357 1:359-694 1:359-694
 @ ./src/templates/ArticleEntry.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/ResourceTypeFilter.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Variable "$title" of type "[String]" used in position expecting type "[ID]".

GraphQL request:39:7
38 |
39 | query($title: [String], $page: Int) {
   |       ^
40 |   records: allResource(filter:{type:{contains:$title}},sortBy:"createdAt", order:DESC, perPage: 9, page: $page) @paginate {

GraphQL request:40:47
40 |   records: allResource(filter:{type:{contains:$title}},sortBy:"createdAt", order
   |                                               ^
   | :DESC, perPage: 9, page: $page) @paginate {
    at Object.module.exports (D:\github\discorso\node_modules\gridsome\lib\plugins\vue-components\lib\loaders\page-query.js:33:23)

 @ ./src/templates/ResourceTypeFilter.vue?vue&type=custom&index=0&blockType=page-query 1:0-344 1:360-363 1:365-706 1:365-706
 @ ./src/templates/ResourceTypeFilter.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/ResourceTagFilter.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Variable "$title" of type "[String]" used in position expecting type "[ID]".

GraphQL request:39:7
38 |
39 | query($title: [String], $page:Int) {
   |       ^
40 |   records: allResource(filter:{tags:{contains:$title}},sortBy:"createdAt", order:DESC, perPage: 9, page: $page) @paginate {

GraphQL request:40:47
40 |   records: allResource(filter:{tags:{contains:$title}},sortBy:"createdAt", order
   |                                               ^
   | :DESC, perPage: 9, page: $page) @paginate {
    at Object.module.exports (D:\github\discorso\node_modules\gridsome\lib\plugins\vue-components\lib\loaders\page-query.js:33:23)

 @ ./src/templates/ResourceTagFilter.vue?vue&type=custom&index=0&blockType=page-query 1:0-343 1:359-362 1:364-704 1:364-704
 @ ./src/templates/ResourceTagFilter.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 WAIT  Compiling...10:29:52

 ERROR  Failed to compile with 3 errors10:29:53

 error  in ./src/templates/ArticleEntry.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Variable "$tags" of type "[String]" used in position expecting type "[ID]".

GraphQL request:42:31
41 |
42 | query Article($recordId: ID!, $tags: [String]) {
   |                               ^
43 |   entry : article(id: $recordId) {

GraphQL request:61:58
60 |   related: allArticle(
61 |     filter: { id: { ne: $recordId }, tags: {containsAny: $tags} }
   |                                                          ^
62 |   ) {
    at Object.module.exports (D:\github\discorso\node_modules\gridsome\lib\plugins\vue-components\lib\loaders\page-query.js:33:23)

 @ ./src/templates/ArticleEntry.vue?vue&type=custom&index=0&blockType=page-query 1:0-338 1:354-357 1:359-694 1:359-694
 @ ./src/templates/ArticleEntry.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/ResourceTypeFilter.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Variable "$title" of type "[String]" used in position expecting type "[ID]".

GraphQL request:39:7
38 |
39 | query($title: [String], $page: Int) {
   |       ^
40 |   records: allResource(filter:{type:{contains:$title}},sortBy:"createdAt", order:DESC, perPage: 9, page: $page) @paginate {

GraphQL request:40:47
40 |   records: allResource(filter:{type:{contains:$title}},sortBy:"createdAt", order
   |                                               ^
   | :DESC, perPage: 9, page: $page) @paginate {
    at Object.module.exports (D:\github\discorso\node_modules\gridsome\lib\plugins\vue-components\lib\loaders\page-query.js:33:23)

 @ ./src/templates/ResourceTypeFilter.vue?vue&type=custom&index=0&blockType=page-query 1:0-344 1:360-363 1:365-706 1:365-706
 @ ./src/templates/ResourceTypeFilter.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/ResourceTagFilter.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Variable "$title" of type "[String]" used in position expecting type "[ID]".

GraphQL request:39:7
38 |
39 | query($title: [String], $page:Int) {
   |       ^
40 |   records: allResource(filter:{tags:{contains:$title}},sortBy:"createdAt", order:DESC, perPage: 9, page: $page) @paginate {

GraphQL request:40:47
40 |   records: allResource(filter:{tags:{contains:$title}},sortBy:"createdAt", order
   |                                               ^
   | :DESC, perPage: 9, page: $page) @paginate {
    at Object.module.exports (D:\github\discorso\node_modules\gridsome\lib\plugins\vue-components\lib\loaders\page-query.js:33:23)

 @ ./src/templates/ResourceTagFilter.vue?vue&type=custom&index=0&blockType=page-query 1:0-343 1:359-362 1:364-704 1:364-704
 @ ./src/templates/ResourceTagFilter.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js


```

**Comment by noxify** [comment]
Hi @paulvanbladel 

thanks for reporting. 

I will check this. 

Seems there are some changes between the last tested version (0.7.13?) and the current one (0.7.19).

**Comment by Eduardoavargas** [comment]
I solved it by the hour, changing the type of String to ID in 3 files.
templates/ArticleEntry `query Article($recordId: ID!, $tags: [String]) to query Article($recordId: ID!, $tags: [ID])`
templates/ResourceTagFilter `query($title: [String], $page:Int) to query($title: [ID], $page:Int)` 
templates/ResouceTypeFilter `query($title: [String], $page: Int) to query($title: [ID], $page: Int)`

**Comment by noxify** [comment]
Sorry for the late response - The query issue is now fixed.

The problem with the duplicate key is more related to the `source-filesystem` logic.

I'm currently porting the starter from Bootstrap to tailwind, where I will try to solve it with a workaround.
But since this is just a warning, I don't think it has any impact.

I will close this issue for now - if you think, I have missed something, feel free to re-open the issue.
